schema_version = "fidb-recipe/v3"
mode = "native"
name = "glib"
version = "2.88.3"
url = "https://download.gnome.org/sources/glib/2.88/glib-2.88.3.tar.xz"
sha256 = "ab24d24e698dfa1e408b7bcdb508f4aafc906185a8b8ce72fdf79bbbdc9b383b"
source_directory = "glib-2.88.3"
project_markers = ["meson.build", "glib/glib.h"]
allowed_build_systems = ["glib-meson", "meson"]
preferred_build_system = "glib-meson"
static_archives = [
  "libglib-2.0.a",
  "libgmodule-2.0.a",
  "libgobject-2.0.a",
  "libgio-2.0.a",
]

[[build_inputs]]
kind = "meson-package-cache"
name = "pcre2-source"
version = "10.46"
url = "https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.46/pcre2-10.46.tar.bz2"
sha256 = "15fbc5aba6beee0b17aecb04602ae39432393aba1ebd8e39b7cabf7db883299f"
filename = "pcre2-10.46.tar.bz2"

[[build_inputs]]
kind = "meson-package-cache"
name = "pcre2-wrap-patch"
version = "10.46-1"
url = "https://wrapdb.mesonbuild.com/v2/pcre2_10.46-1/get_patch"
sha256 = "761d16c89b9c13812842916b7ee970650ee7c1810f83bc567351faf7365b66be"
filename = "pcre2_10.46-1_patch.zip"

[[build_inputs]]
kind = "meson-package-cache"
name = "libffi-source"
version = "3.5.2"
url = "https://github.com/libffi/libffi/releases/download/v3.5.2/libffi-3.5.2.tar.gz"
sha256 = "f3a3082a23b37c293a4fcd1053147b371f2ff91fa7ea1b2a52e335676bac82dc"
filename = "libffi-3.5.2.tar.gz"

[[build_inputs]]
kind = "meson-package-cache"
name = "libffi-wrap-patch"
version = "3.5.2-1"
url = "https://wrapdb.mesonbuild.com/v2/libffi_3.5.2-1/get_patch"
sha256 = "1ee3035d92e4df3541d0b2b8d192d2fa183b46e4a3d68c00d8f71ede354bee74"
filename = "libffi_3.5.2-1_patch.zip"

[[build_inputs]]
kind = "meson-package-cache"
name = "zlib-source"
version = "1.3.1"
url = "https://zlib.net/fossils/zlib-1.3.1.tar.gz"
sha256 = "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"
filename = "zlib-1.3.1.tar.gz"

[[build_inputs]]
kind = "meson-package-cache"
name = "zlib-wrap-patch"
version = "1.3.1-1"
url = "https://wrapdb.mesonbuild.com/v2/zlib_1.3.1-1/get_patch"
sha256 = "e79b98eb24a75392009cec6f99ca5cdca9881ff20bfa174e8b8926d5c7a47095"
filename = "zlib_1.3.1-1_patch.zip"

[[build_inputs]]
kind = "meson-package-cache"
name = "proxy-libintl-source"
version = "0.5"
url = "https://github.com/frida/proxy-libintl/archive/refs/tags/0.5.tar.gz"
sha256 = "f7a1cbd7579baaf575c66f9d99fb6295e9b0684a28b095967cfda17857595303"
filename = "proxy-libintl-0.5.tar.gz"
