"""Freeze a dynamic width campaign into deterministic, disarmed queue plans.

The time model is deliberately dynamic: new timing evidence may repack its
blocks.  This module is the explicit boundary which turns one reviewed
projection into portable ``fidb-plan/v1`` files.  It never arms, synchronizes,
or executes the queue.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import tempfile
import tomllib

from .batch_time_model import DEFAULT_MODEL_PATH, compile_time_block_plan
from .c_width import compile_c_width
from .config import load_configuration
from .plan_request import queue_identity_digest, resolve_plan
from .width_batch import load_width_batch

MATERIALIZATION_SCHEMA = "fidb-materialized-campaign/v1"
DEFAULT_OUTPUT_ROOT = Path("plans/materialized")
MANIFEST_NAME = "manifest.toml"


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _canonical_digest(value: object) -> str:
    payload = json.dumps(
        value, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode("utf-8")
    return _sha256(payload)


def _toml_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _toml_array(values: list[str] | tuple[str, ...]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def _project_relative(root: Path, value: str | Path, context: str) -> Path:
    path = Path(value)
    if path.is_absolute() or ".." in path.parts:
        raise ValueError(f"{context} must stay inside project root")
    resolved = (root / path).resolve()
    try:
        relative = resolved.relative_to(root)
    except ValueError as error:
        raise ValueError(f"{context} must stay inside project root") from error
    return relative


def _ordered_width_axes(
    root: Path, batch: dict[str, object]
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    width_path = Path(str(batch["authorities"]["width"]))  # type: ignore[index]
    width = compile_c_width(root, width_path.stem)
    selected = [
        row
        for row in width["applicability"]  # type: ignore[index]
        if row["state"] in {"executable", "unavailable"}
    ]
    unavailable = [row for row in selected if row["state"] != "executable"]
    if unavailable:
        route_ids = sorted({str(row["route_id"]) for row in unavailable})
        raise ValueError(
            "materialization requires every selected route to be locally qualified; "
            f"unavailable: {', '.join(route_ids)}"
        )
    selected_pairs = {
        (str(row["route_id"]), str(row["treatment_id"])) for row in selected
    }
    route_ids = tuple(
        str(route["id"])
        for route in width["routes"]  # type: ignore[index]
        if any(pair[0] == route["id"] for pair in selected_pairs)
    )
    first_recipe = str(batch["libraries"][0]["recipe_id"])  # type: ignore[index]
    configuration = load_configuration(root / "worker.toml", (first_recipe,))
    treatment_ids = tuple(
        treatment.id
        for treatment in configuration.treatments
        if any(pair[1] == treatment.id for pair in selected_pairs)
    )
    cartesian = {
        (route_id, treatment_id)
        for route_id in route_ids
        for treatment_id in treatment_ids
    }
    if not route_ids or not treatment_ids or selected_pairs != cartesian:
        raise ValueError(
            "current fidb-plan/v1 native matrices require rectangular route/treatment "
            "applicability; split or extend the plan schema before materializing"
        )
    executions = int(batch["summary"]["executions_per_library"])  # type: ignore[index]
    if executions != len(selected_pairs):
        raise ValueError(
            "current fidb-plan/v1 cannot express downstream artifact, analysis, or "
            "replay multipliers; extend it before materializing this width"
        )
    return route_ids, treatment_ids


def _render_plan(
    campaign_id: str,
    block: dict[str, object],
    groups: list[dict[str, object]],
) -> str:
    lines = [
        '# Generated by "fidb-poc materialize-batches". Do not hand edit.',
        'schema_version = "fidb-plan/v1"',
        f"name = {_toml_string(block['id'])}",
        "",
        "[policy]",
        f"max_cells = {int(block['executions'])}",
        'priority = "normal"',
        "",
        "[coverage]",
        "# Native treatments already carry their exact factor-variant identity.",
        "factor_variants = []",
        "",
        "[queue]",
        'strategy = "recipe-then-variant"',
        f"recipe_order = {_toml_array([str(row['recipe_id']) for row in block['items']])}",
    ]
    for index, group in enumerate(groups, start=1):
        lines.extend(
            [
                "",
                "[[matrix]]",
                "id = "
                + _toml_string(
                    f"{campaign_id}-block-{int(block['position']):02d}-width-{index:02d}"
                ),
                'kind = "width-native"',
                f"width_batch = {_toml_string(group['batch_authority'])}",
                f"recipes = {_toml_array(group['recipe_ids'])}",
                f"routes = {_toml_array(group['route_ids'])}",
                f"treatments = {_toml_array(group['treatment_ids'])}",
            ]
        )
    return "\n".join(lines) + "\n"


def _queue_identity(plan: dict[str, object]) -> list[dict[str, object]]:
    rows = []
    for row in plan["queue_preview"]:  # type: ignore[index]
        if row["state"] != "planned":
            raise ValueError(
                f"materialized cell {row['base_cell']} is blocked: "
                + "; ".join(str(value) for value in row["blockers"])
            )
        rows.append(
            {
                "position": int(row["position"]),
                "base_cell": str(row["base_cell"]),
                "factor_variants": list(row["factor_variants"]),
                "state": str(row["state"]),
            }
        )
    return rows


def _resolve_rendered_plan(
    root: Path, filename: str, payload: str
) -> dict[str, object]:
    with tempfile.TemporaryDirectory(prefix="fidb-materialize-") as temporary:
        path = Path(temporary) / filename
        path.write_text(payload, encoding="utf-8")
        return resolve_plan(path, root)


def compile_materialization(
    project_root: str | Path,
    model_path: str | Path = DEFAULT_MODEL_PATH,
    output_root: str | Path = DEFAULT_OUTPUT_ROOT,
) -> dict[str, object]:
    """Compile one frozen, portable campaign description without writing files."""

    root = Path(project_root).expanduser().resolve()
    relative_output_root = _project_relative(root, output_root, "output root")
    time_plan = compile_time_block_plan(root, model_path)
    campaign_id = str(time_plan["id"])
    campaign_directory = relative_output_root / campaign_id

    batches: dict[str, dict[str, object]] = {}
    axes: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {}
    all_recipe_ids = []
    for block in time_plan["blocks"]:  # type: ignore[index]
        for item in block["items"]:
            authority = str(item["batch_authority"])
            if authority not in batches:
                batches[authority] = load_width_batch(root, root / authority)
            batch = batches[authority]
            if authority not in axes:
                axes[authority] = _ordered_width_axes(root, batch)
            matches = [
                row
                for row in batch["libraries"]  # type: ignore[index]
                if row["id"] == item["source_id"] and row["version"] == item["version"]
            ]
            if len(matches) != 1:
                raise ValueError(
                    f"time block source {item['source_id']}@{item['version']} no longer "
                    f"matches {authority}"
                )
            item["recipe_id"] = matches[0]["recipe_id"]
            all_recipe_ids.append(str(matches[0]["recipe_id"]))

    configuration = load_configuration(
        root / "worker.toml", tuple(dict.fromkeys(all_recipe_ids))
    )
    recipes = {f"{row.name}@{row.version}": row for row in configuration.libraries}
    for batch in batches.values():
        for library in batch["libraries"]:  # type: ignore[index]
            recipe = recipes.get(str(library["recipe_id"]))
            if recipe is None:
                raise ValueError(f"missing reviewed recipe {library['recipe_id']}")
            if recipe.url != library["url"] or recipe.sha256 != library["sha256"]:
                raise ValueError(
                    f"reviewed recipe {library['recipe_id']} no longer matches its "
                    "pinned source"
                )

    materialized_blocks = []
    rendered_plans: dict[str, str] = {}
    total_executions = 0
    for block in time_plan["blocks"]:  # type: ignore[index]
        grouped: dict[str, dict[str, object]] = {}
        for item in block["items"]:
            authority = str(item["batch_authority"])
            route_ids, treatment_ids = axes[authority]
            group = grouped.setdefault(
                authority,
                {
                    "batch_authority": authority,
                    "recipe_ids": [],
                    "route_ids": list(route_ids),
                    "treatment_ids": list(treatment_ids),
                },
            )
            group["recipe_ids"].append(str(item["recipe_id"]))  # type: ignore[index]
        filename = f"block-{int(block['position']):02d}.toml"
        plan_path = campaign_directory / filename
        payload = _render_plan(campaign_id, block, list(grouped.values()))
        resolved = _resolve_rendered_plan(root, filename, payload)
        identity = _queue_identity(resolved)
        executions = len(identity)
        if executions != int(block["executions"]):
            raise ValueError(
                f"{block['id']} materialized {executions} cells; expected "
                f"{block['executions']}"
            )
        rendered_plans[str(plan_path)] = payload
        materialized_blocks.append(
            {
                "id": str(block["id"]),
                "position": int(block["position"]),
                "state": "materialized-disarmed",
                "plan": str(plan_path),
                "plan_sha256": _sha256(payload.encode("utf-8")),
                "queue_digest": queue_identity_digest(identity),
                "executions": executions,
                "estimated_hours": block["estimated_hours"],
                "planning_lower_hours": block["planning_lower_hours"],
                "planning_upper_hours": block["planning_upper_hours"],
                "source_ids": [str(row["source_id"]) for row in block["items"]],
                "recipe_ids": [str(row["recipe_id"]) for row in block["items"]],
            }
        )
        total_executions += executions

    if total_executions != int(time_plan["summary"]["executions"]):  # type: ignore[index]
        raise ValueError(
            "materialized campaign execution total does not match time plan"
        )
    body = {
        "schema_version": MATERIALIZATION_SCHEMA,
        "id": campaign_id,
        "label": time_plan["label"],
        "state": "materialized-disarmed",
        "language_id": time_plan["language_id"],
        "time_model": time_plan["authority_path"],
        "time_plan_digest": time_plan["plan_digest"],
        "performance_profile": time_plan["performance_profile"]["id"],  # type: ignore[index]
        "output_directory": str(campaign_directory),
        "manifest_path": str(campaign_directory / MANIFEST_NAME),
        "summary": {
            "blocks": len(materialized_blocks),
            "libraries": int(time_plan["summary"]["libraries"]),  # type: ignore[index]
            "executions": total_executions,
            "estimated_hours": time_plan["summary"]["estimated_hours"],  # type: ignore[index]
            "planning_lower_hours": time_plan["summary"]["planning_lower_hours"],  # type: ignore[index]
            "planning_upper_hours": time_plan["summary"]["planning_upper_hours"],  # type: ignore[index]
        },
        "source_digests": time_plan["source_digests"],
        "blocks": materialized_blocks,
    }
    document = {**body, "materialization_digest": _canonical_digest(body)}
    document["rendered_plans"] = rendered_plans
    return document


def _render_manifest(document: dict[str, object]) -> str:
    lines = [
        '# Generated by "fidb-poc materialize-batches". Do not hand edit.',
        f"schema_version = {_toml_string(document['schema_version'])}",
        f"id = {_toml_string(document['id'])}",
        f"label = {_toml_string(document['label'])}",
        f"state = {_toml_string(document['state'])}",
        f"language_id = {_toml_string(document['language_id'])}",
        f"time_model = {_toml_string(document['time_model'])}",
        f"time_plan_digest = {_toml_string(document['time_plan_digest'])}",
        f"performance_profile = {_toml_string(document['performance_profile'])}",
        f"output_directory = {_toml_string(document['output_directory'])}",
        f"materialization_digest = {_toml_string(document['materialization_digest'])}",
        "",
        "[summary]",
    ]
    for key, value in document["summary"].items():  # type: ignore[index]
        lines.append(f"{key} = {json.dumps(value)}")
    lines.extend(["", "[source_digests]"])
    for key, value in document["source_digests"].items():  # type: ignore[index]
        lines.append(f"{key} = {_toml_string(value)}")
    for block in document["blocks"]:  # type: ignore[index]
        lines.extend(
            [
                "",
                "[[blocks]]",
                f"id = {_toml_string(block['id'])}",
                f"position = {block['position']}",
                f"state = {_toml_string(block['state'])}",
                f"plan = {_toml_string(block['plan'])}",
                f"plan_sha256 = {_toml_string(block['plan_sha256'])}",
                f"queue_digest = {_toml_string(block['queue_digest'])}",
                f"executions = {block['executions']}",
                f"estimated_hours = {json.dumps(block['estimated_hours'])}",
                f"planning_lower_hours = {json.dumps(block['planning_lower_hours'])}",
                f"planning_upper_hours = {json.dumps(block['planning_upper_hours'])}",
                f"source_ids = {_toml_array(block['source_ids'])}",
                f"recipe_ids = {_toml_array(block['recipe_ids'])}",
            ]
        )
    return "\n".join(lines) + "\n"


def write_materialization(
    document: dict[str, object], project_root: str | Path
) -> None:
    """Atomically write generated plans and their disarmed manifest."""

    root = Path(project_root).expanduser().resolve()
    rendered = document.get("rendered_plans")
    if not isinstance(rendered, dict):
        raise ValueError("compiled materialization has no rendered plans")
    writes = {str(path): str(payload) for path, payload in rendered.items()}
    writes[str(document["manifest_path"])] = _render_manifest(document)
    for relative, payload in writes.items():
        path = root / _project_relative(root, relative, "materialized output")
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(f".{path.name}.tmp")
        temporary.write_text(payload, encoding="utf-8")
        temporary.replace(path)


def check_materialization(
    document: dict[str, object], project_root: str | Path
) -> dict[str, object]:
    """Check that disk contains exactly the currently compiled disarmed output."""

    root = Path(project_root).expanduser().resolve()
    expected = {
        **{str(path): str(payload) for path, payload in document["rendered_plans"].items()},  # type: ignore[index]
        str(document["manifest_path"]): _render_manifest(document),
    }
    mismatches = []
    for relative, payload in expected.items():
        path = root / _project_relative(root, relative, "materialized output")
        if not path.is_file():
            mismatches.append({"path": relative, "reason": "missing"})
        elif path.read_text(encoding="utf-8") != payload:
            mismatches.append({"path": relative, "reason": "content-drift"})
    return {
        "state": "current" if not mismatches else "drifted",
        "checked_files": len(expected),
        "mismatches": mismatches,
    }


def load_materialization_manifest(path: str | Path) -> dict[str, object]:
    """Read the generated TOML manifest for UI and operator inspection."""

    document = tomllib.loads(Path(path).read_text(encoding="utf-8"))
    if document.get("schema_version") != MATERIALIZATION_SCHEMA:
        raise ValueError(f"unsupported materialization manifest: {path}")
    return document
